### ISSUE TITLE
ImportError: cannot import name abc

### ISSUE THREAD

**Issue by emaniacs** [simoncoulton/watson#2]
I try to install using pip with virtual environment, and i got that error.
The error coming from _watson/common/imports.py_ **line 2**

**Comment by simoncoulton** [comment]
Is the Python in your virtualenv version 3.3? Could you provide me with a few more details about the environment so I can try to replicate it here? Thanks

**Comment by emaniacs** [comment]
I use 2.7.3, is that the problem?

**Comment by simoncoulton** [comment]
Unfortunately yes, Watson only supports Python 3.3 and up at the moment. Create a new virtualenv with 3.3 and give it a try again.
