### ISSUE TITLE
simple response 

### ISSUE THREAD

**Issue by dalirnet** [simoncoulton/watson#3]
how to send fast response in watson?
like _(php)_ simple echo without template engine.

thanks

**Comment by simoncoulton** [comment]
There's really two ways you could go about it, depending on what your needs are:

```python
# -*- coding: utf-8 -*-
from watson.framework import controllers


class SomeController(controllers.Rest):

    def GET(self):        
        return messages.Response(body='This is a test')
```

or

```python
# -*- coding: utf-8 -*-
from watson.framework import controllers


class SomeController(controllers.Rest):

    def GET(self):
        self.response.body = 'This is a test'
        return self.response
```

The second option is preferable if you're somehow modifying the response object that's part of the request context elsewhere within your application.

**Comment by dalirnet** [comment]
very simple solution 
thanks.
